spring:
  application:
    name: eureka-provider
server:
  port: 8081

eureka:
  client:
    service-url:
      # 单机
       defaultZone: http://admin:654321@127.0.0.1:8080/eureka
      # 集群
#      defaultZone: http://admin:654321@127.0.0.1:8888/eureka/,http://admin:654321@127.0.0.1:9999/eureka/
  instance:
    # 采用IP注册
    prefer-ip-address: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
