spring:
  application:
    name: eureka-provider
server:
  port: 8082

eureka:
  client:
    service-url:
      # 单机
      defaultZone: http://admin:654321@127.0.0.1:8080/eureka
      # 集群
      # defaultZone: http://admin:654321@127.0.0.1:8888/eureka/,http://admin:654321@127.0.0.1:9999/eureka/
  instance:
    # 使用IP地址注册
    prefer-ip-address: true
    # 自定义instanceID格式，默认是主机名:服务名称:服务端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 自定义实例跳转链接
    # status-page-url:
    # Eureka服务续约频率，默认30s
    lease-renewal-interval-in-seconds: 30
    # Eureka服务失效时间，默认90s
    lease-expiration-duration-in-seconds: 90