spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 654321
server:
  port: 8080

eureka:
  client:
    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    fetch-registry: false