spring:
  application:
    name: eureka-consumer
server:
  port: 8083

eureka:
  client:
    service-url:
      # 单机
      defaultZone: http://admin:654321@127.0.0.1:8080/eureka
    # 集群
#     defaultZone: http://admin:654321@127.0.0.1:8888/eureka,http://admin:654321@127.0.0.1:9999/eureka

# feignClient日志配置
logging:
  level:
    com.dayang.client.ProviderFeignClient: DEBUG